name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  node-compat:
    name: 'Node ${{ matrix.node-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: install dependencies
        run: pnpm install
      - run: pnpm test

  release-it-compat:
    name: 'release-it@${{ matrix.release-it-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release-it-version:
          ['^17.0.0', '^18.0.0', '^19.0.0']

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: install dependencies
        run: pnpm install
      - run: pnpm install --save-dev release-it@${{ matrix.release-it-version }}
      - run: pnpm test

  release:
    name: 'release'
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - release-it-compat
      - node-compat
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: install dependencies
        run: pnpm install
      - name: set git author for release to github bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Release the package
        run: pnpm run release
