name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  node-compat:
    name: 'Node ${{ matrix.node-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: install dependencies
        run: pnpm install
      - run: pnpm test

  release-it-compat:
    name: 'release-it@${{ matrix.release-it-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release-it-version:
          ['^17.0.0', '^18.0.0', '^19.0.0']

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install dependencies
        run: pnpm install
      - run: pnpm install --save-dev release-it@${{ matrix.release-it-version }}
      - run: pnpm test

  release:
    name: 'release'
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - release-it-compat
      - node-compat
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: install dependencies
        run: pnpm install
      - run: pnpm login && pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
