name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  node-compat:
    name: 'Node ${{ matrix.node-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: install dependencies
        run: pnpm install
      - run: pnpm test

  release-it-compat:
    name: 'release-it@${{ matrix.release-it-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release-it-version:
          ['^17.0.0', '^18.0.0', '^19.0.0']

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: install dependencies
        run: pnpm install
      - run: pnpm install --save-dev release-it@${{ matrix.release-it-version }}
      - run: pnpm test

  release:
    name: 'release'
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - release-it-compat
      - node-compat
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: install dependencies
        run: pnpm ci
      - run: pnpm run release
